### ISSUE TITLE
Create request for getting all shedule for group

### ISSUE THREAD

**Issue by leonis13579** [RTUITLab/Schedule-RTU-API#26]
Нужно сделать запрос на получение всего расписания группы на обе недели в качестве одного запроса, а не двух.

**Comment by Nekolya** [comment]
[Реализовано(https://github.com/RTUITLab/Schedule-RTU/commit/3b6b899d0b7faf9b27ef6dcb15334d1c9b748dbd), но нуждается в доработке
Можно использовать сейчас, формат данных не измениться, однако расписание там немного неполное

**Comment by Nekolya** [comment]
[Сделано](https://github.com/RTUITLab/Schedule-RTU-API/commit/69bd94992fc8baffd0e7b809faf0a7a0a176d85f) 
Разные пары в одном слоте разделяются с помощью "\n"
