### ISSUE TITLE
Don't display invalid data

### ISSUE THREAD

**Issue by Eloren1** [RTUITLab/Schedule-RTU-API#34]
В некоторых группах имеются такие предметы — `…………`, которые показываются в расписании. Наверное, можно не отображать такие пары. Количество точек варьируется.

![Screenshot_105](https://user-images.githubusercontent.com/46666053/114076609-81d74680-98af-11eb-99de-4e1986e890e0.png)

**Comment by CAPCHIK** [comment]
@Nekolya Возможно стоит сделать некое место, где будут обрабатываться последовательно многие такие ситуации, чтобы можно было оперативно и быстро добавлять такие исключения

**Comment by 0niel** [comment]
Точки и прочий мусор по типу пробелов исправлены тут: https://github.com/RTUITLab/Schedule-RTU-API/pull/39
