### ISSUE TITLE
Empty type

### ISSUE THREAD

**Issue by Delivery-Klad** [RTUITLab/Schedule-RTU-API#45]
![image](https://user-images.githubusercontent.com/49003989/142019384-2d5da990-8f23-406f-abd0-0279f100acb4.png)

**Comment by CAPCHIK** [comment]
Приятно при таких ошибках прикладывать сам ответ, и json-path к этому полю
Учитывая, что API публичное - так делать вполне можно, файлом ответ от сервера, и текстом json-path

**Comment by Delivery-Klad** [comment]
api/schedule/ИКБО-08-18/today

[response_1637215331444.txt](https://github.com/RTUITLab/Schedule-RTU-API/files/7560337/response_1637215331444.txt)

**Comment by Nekolya** [comment]
В основном обработано. Пустые типы остались у пар, а которых тип явно не указан (например физкультура)
